name: Build and Test Mobile App DEV STAGE

on: [push, pull_request]

jobs:
  build:
    name: Build Application APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.6'
          channel: 'stable'

      

      - run: flutter pub get
      - run: flutter build apk --debug --split-per-abi
      - run: flutter pub run test test/
#      - run: flutter pub run test_coverage
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          file: coverage/lcov.info
